POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "testuser4@sample.com",
  "nickname": "testuser4",
  "password": "123123"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "testuser3@sample.com",
  "password": "123123"
}

###
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "password": "123123"
}

###
GET http://localhost:3000/users/me

###
Post http://localhost:3000/users/logout

###

GET http://localhost:3000/articles

###

GET http://localhost:3000/products

### 

POST http://localhost:3000/products/create
Content-Type: application/json

{
  "name": "에어팟 프로 3",
    "description": "미개봉 신제품",
    "price": 300000,
    "tags": ["애플", "블루투스이어폰", "에어팟"]
}
###

PATCH http://localhost:3000/products/update/2
Content-Type: application/json

{
    "price": 320000
}

###
Post http://localhost:3000/products/comments/1/create
Content-Type: application/json

{
"content": "얼마나 썼나요"
}

###
Post http://localhost:3000/articles/comments/1/create
Content-Type: application/json

{
"content": "반갑습니다 ^^"
}


###
PATCH http://localhost:3000/articles/comments/1/update
Content-Type: application/json

{
"content": "안녕하세요 반갑습니다 ^^"
}


###
PATCH http://localhost:3000/products/comments/1/update
Content-Type: application/json

{
"content": "언제 구매하셨나요? 얼마나 쓰셨나요"
}

###
POST http://localhost:3000/articles/create
Content-Type: application/json

{
  "title": "안녕하세요",
  "content": "안녕하세요 오늘 가입했어요"
}

###
PATCH  http://localhost:3000/articles/update/4
Content-Type: application/json

{
  "title": "반가워요"
}


###
POST http://localhost:3000/likes/articles/1


###
POST http://localhost:3000/likes/products/1

###
GET  http://localhost:3000/articles/my-article

###
GET  http://localhost:3000/products/my-product

###
GET  http://localhost:3000/products/me/liked-products

###
GET  http://localhost:3000/articles

###

DELETE http://localhost:3000/users/12

###

DELETE http://localhost:3000/products/2

###
DELETE http://localhost:3000/products/comments/3

###
DELETE http://localhost:3000/articles/comments/3


###
DELETE http://localhost:3000/articles/6