POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "testuser1@sample.com",
  "nickname": "testuser1",
  "password": "123123"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "testuser1@sample.com",
  "password": "12341234"
}

###
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "password": "12341234"
}

###
GET http://localhost:3000/users/me

###
Post http://localhost:3000/users/logout

###

GET http://localhost:3000/articles

### 

POST http://localhost:3000/products/create
Content-Type: application/json

{
  "name": "고양이 캣타워 원목",
    "description": "구매해주세요 제발",
    "price": 100000,
    "tags": ["고양이", "캣타워", "원목"]
}
###

PATCH http://localhost:3000/products/update/2
Content-Type: application/json

{
    "price": 350000
}

###
Post http://localhost:3000/products/comments/1/create
Content-Type: application/json

{
"content": "하자 없나요"
}

###
Post http://localhost:3000/articles/comments/7/create
Content-Type: application/json

{
"content": "저도 얼마 전에 제습기 사니 좋더라구요"
}


###
PATCH http://localhost:3000/articles/comments/3/update
Content-Type: application/json

{
"content": "저도 얼마 전에 제습기 샀는데 안 쓰는거랑 다르더라구요"
}


###
PATCH http://localhost:3000/products/comments/1/update
Content-Type: application/json

{
"content": "액정 깨짐이나 기스 없나요"
}

###
POST http://localhost:3000/articles/create
Content-Type: application/json

{
  "title": "날씨가 너무 더워요",
  "content": "제습기 필수네요 "
}

###
PATCH  http://localhost:3000/articles/update/4
Content-Type: application/json

{
  "title": "반가워요"
}


###
POST http://localhost:3000/likes/articles/1


###
POST http://localhost:3000/likes/products/3

###
GET  http://localhost:3000/articles/my-article

###
GET  http://localhost:3000/products/my-product

###
GET  http://localhost:3000/products/me/liked-products

###
GET  http://localhost:3000/articles

###

DELETE http://localhost:3000/users/12

###

DELETE http://localhost:3000/products/2

###
DELETE http://localhost:3000/products/comments/3

###
DELETE http://localhost:3000/articles/comments/3


###
DELETE http://localhost:3000/articles/6